select * from customer limit 20 

--Q1. What is the total revenue generated by male vs .female customer ?
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender"

--Q2. Which customer used a discount but still spend more than avg purchese ?
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >= (
      SELECT AVG("Purchase Amount (USD)")
      FROM customer
  );

--Q3. Which are the top 5 products with the highest avg review rating?
SELECT "Item Purchased",
       AVG("Review Rating") AS "Average Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5


--Q4 compare  the avg purchase amount betn standard and expresss shipping ?
SELECT "Shipping Type",
       AVG("Purchase Amount (USD)") AS average_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type"


--Q5 do subscription customers spend more ? compare avg spend and total revenue 
--between subscribers and non-subscribers ?
SELECT "Subscription Status",
       COUNT("Customer ID") AS "total_customer",
       ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS "avg_spend",
       ROUND(SUM("Purchase Amount (USD)")::numeric, 2) AS "total_revenue"
FROM customer
GROUP BY "Subscription Status"
ORDER BY "total_revenue" DESC, "avg_spend" DESC;

--Q6  which 5 products have the highest % of purchagse with discounts applied ?
SELECT "Item Purchased",
       ROUND(
           SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)::numeric
           / COUNT(*) * 100,
           2
       ) AS discount_rate
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;

--Q7 Segment customer into new ,returning ,and loyal based on their total 
--number of previous purchages ,and show the count of each segment ?
WITH customer_type AS (
    SELECT "Customer ID",
           "Previous Purchases",
           CASE
               WHEN "Previous Purchases" = 1 THEN 'New'
               WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS "number of customer"
FROM customer_type
GROUP BY customer_segment;

--Q8 what are the top 3 most purchased product within each category?
WITH item_count AS (
    SELECT
        "Category",
        "Item Purchased",
        COUNT("Customer ID") AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY "Category"
            ORDER BY COUNT("Customer ID") DESC
        ) AS item_rank
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT
    item_rank,
    "Category",
    "Item Purchased",
    total_orders
FROM itERROR:  syntax error at or near "("
LINE 3:        SUM("Purchase Amount (USD)") AS total_revenue
                  ^ 

SQL state: 42601
Character: 87em_count
WHERE item_rank <= 3
ORDER BY "Category", item_rank;

--Q9 are customers who are repeat buyer (moree 5 previous puchase ) also subscribe
SELECT "Subscription Status",
       COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";
---column name finding 
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer';

--Q10  what is the revenue constribution of each age grp ?
SELECT
    CASE
        WHEN "Age" < 25 THEN 'Under 25'
        WHEN "Age" BETWEEN 25 AND 34 THEN '25-34'
        WHEN "Age" BETWEEN 35 AND 44 THEN '35-44'
        ELSE '45+'
    END AS age_group,
    ROUND(
        SUM("Purchase Amount (USD)") * 100.0 /
        (SELECT SUM("Purchase Amount (USD)") FROM customer),
        2
    ) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;